$ErrorActionPreference = 'Stop'

$root = Split-Path -Parent $PSScriptRoot
$brandDir = Join-Path $root 'images\\brands'
$manifestPath = Join-Path $brandDir 'brands-manifest.js'
$allowedExtensions = '.webp', '.png', '.jpg', '.jpeg', '.svg'

$nameOverrides = @{
    'ar' = 'AR'
    'annovi_reverberi' = 'Annovi Reverberi'
    'black_decker' = 'Black+Decker'
    'bluebird' = 'Blue Bird'
    'dab' = 'DAB'
    'dewalt' = 'DEWALT'
    'fox' = 'FOX'
    'hikoki' = 'HiKOKI'
    'husqvarna_1' = 'Husqvarna'
    'husqvarna_2_automower' = 'Husqvarna Automower'
    'lavor_pro' = 'Lavor PRO'
    'nidec_tea' = 'Nidec TEA'
    'oft' = 'OFT'
    'karcher' = 'Kärcher'
    'segway_navimow' = 'Segway Navimow'
}

function Get-BrandLabel {
    param(
        [Parameter(Mandatory = $true)]
        [string]$BaseName
    )

    if ($nameOverrides.ContainsKey($BaseName)) {
        return $nameOverrides[$BaseName]
    }

    $label = $BaseName -replace '[_-]+', ' '
    $textInfo = [System.Globalization.CultureInfo]::InvariantCulture.TextInfo

    return $textInfo.ToTitleCase($label.ToLowerInvariant())
}

$items = Get-ChildItem -Path $brandDir -File |
    Where-Object {
        $allowedExtensions -contains $_.Extension.ToLowerInvariant() -and
        $_.Name -ne 'brands-manifest.js'
    } |
    Sort-Object Name |
    ForEach-Object {
        [pscustomobject]@{
            src = 'images/brands/' + $_.Name
            alt = Get-BrandLabel -BaseName $_.BaseName
        }
    }

$json = $items | ConvertTo-Json -Depth 3
$content = @(
    '// Auto-generated by scripts/sync-brands-manifest.ps1'
    'window.__BRAND_LOGOS__ = ' + $json + ';'
    ''
) -join [Environment]::NewLine

$utf8NoBom = New-Object System.Text.UTF8Encoding($false)
[System.IO.File]::WriteAllText($manifestPath, $content, $utf8NoBom)
